### ISSUE TITLE
Data Analysis / SCR - Input files not generated [fixed!], but now cause IDS to crash when used

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#169]
A few weeks ago, Marike posted on the forum about issues running SCR, including the fact that the generation of input files took 5 hours to generate; see [here](https://pantheraids.org/forum.html?p=post%2Frun-analysis-button-for-bayesian-analysis-not-working-10980867%3Fpid%3D1317607994). @PhilipFaure responded saying the problem was fixed and would be included in the next release (beta). I don't believe a GitHub Issue was created for this

However, she just updated to the "next release" (beta v2.26.894) and the generation of input files still takes 5 hours and in the end **doesn't generate any files**. For more details, see her new post [here](https://pantheraids.org/forum.html?p=post%2Fscr-input-files-not-generated-in-beta-v2-26-894-11110551%3Fpid%3D1319539443) where she has also uploaded log files.

She is under a lot of pressure to get surveys analysed as soon as possible.

**Comment by RossPitman** [comment]
I'm assuming Philip fixed this in the latest version, which hasn't been pushed yet. I need the Saudi team to register for IDS first before I can push the next update.

**Comment by RossPitman** [comment]
Can we please check with Marike as to whether this issue is fixed in the new version? Thanks

**Comment by Shannon-Dubay** [comment]
Sent. Will report back with an update when I get it.

**Comment by RossPitman** [comment]
Can we also Marike to update to the latest IDS. Pushed 2.27.896 yesterday which should have an updated version of unmarked. Actually need to push the next IDS version today too. But it's a big download, so she'll need good internet.

**Comment by PhilipFaure** [comment]
Done. Input files take the normal amount of time again and can be downloaded through a downloadHandler.
Closing issue.

**Comment by Shannon-Dubay** [comment]
@RossPitman and @PhilipFaure - apparently after updating (to v.2.27.898, released yesterday) files are still not generated. Jo posted this morning on the original [post](https://pantheraids.org/forum.html?p=post%2Fscr-input-files-not-generated-in-beta-v2-26-894-11110551%3Fpid%3D1319664190) by Marike

**Comment by RossPitman** [comment]
Hopefully @PhilipFaure will be able to let us know what was done here.

**Comment by Shannon-Dubay** [comment]
Jo and Marike pretty desperate for this to be fixed, Jo asking for an update on the situation on the forum ([here](https://pantheraids.org/forum.html?p=post%2Fscr-input-files-not-generated-in-beta-v2-26-894-11110551%3Fpid%3D1321465821)).

**Comment by PhilipFaure** [comment]
Hi @Shannon-Dubay I cannot recreate this problem. If I run IDS latest without any changes in the container from my side, i.e. the way the users will have it, I can generate the SCR files in about two minutes. Are these files not created on your computer either when you run Latest v.2.28.899?

**Comment by PhilipFaure** [comment]
It should have a download handler popping up which asks the user if they want to save the download. This folder then gets saved in the Downloads folder of their machine. Therefore, it does not save in the old location anymore (i.e. ids_volume/data/database/<SURVEY_FOLDER>/..

**Comment by Shannon-Dubay** [comment]
@PhilipFaure I will ask the users to check their downloads folder. 

Could we change this to reflect what we have in the Bulk Image Export module, where the user determines if they want it in the Downloads folder or somewhere else? This not only gives them more control over where their files go, but also clearly indicates that the files will not be created in the location that most users expect.
<img width="1440" alt="Screenshot 2020-11-09 at 08 00 31" src="https://user-images.githubusercontent.com/48274721/98505513-028f0980-2262-11eb-922f-724834933b82.png">

**Comment by Shannon-Dubay** [comment]
Feedback from Jo via the [forum](https://pantheraids.org/forum.html?p=post%2Fscr-input-files-not-generated-in-beta-v2-26-894-11110551%3Fpid%3D1321539997):

_Previously IDS would read from ids_volume>data>database where the folder with SECR files would be. Now it's downloaded in local "Download" folder -no option to download directly in "database" folder in ids_volume. Even after moving that folder back into "database" folder in ids_volume (yes unzipped and renamed with just the survey ID), IDS crashes after clicking "Run Analysis" (Bayes)._

**Comment by Shannon-Dubay** [comment]
Jo's input (from the forum, paraphrased):

The format of the names of the generated SECR folders has changed to counter an overwriting issue (added a time stamp to name), however IDS still automatically looks for the old format folder (survey ID without time stamp). 

Perhaps add a way for the user to indicate the location/select the folder with SECR files?

**Comment by RossPitman** [comment]
Hey @PhilipFaure / @Shannon-Dubay – I'm be looking into this now. I also tried to run the SCR (from database) module and I cannot run an analysis. I then tried to load the input files, which downloaded correctly, within the SCR (from CSV/Rdata) module but IDS had a catastrophic failure--so we also need to include a bunch of redundancy here too.

**Comment by RossPitman** [comment]
UI updated to be more user friendly and process streamlined.
