### ISSUE TITLE
Manual Identification/Batch Rename - not server ready

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#35]
The Batch Rename tool under Manual Identification isn't working for data from the server.

**Comment by RossPitman** [comment]
In what way isn't this working?

**Comment by Shannon-Dubay** [comment]
Sorry just noticed its a problem for both server and local- the "Batch Rename Primary Identification" says "No Individuals Loaded" in the "Individuals" dropdown.

**Comment by RossPitman** [comment]
Fixed in version 1.14.806

**Comment by Shannon-Dubay** [comment]
This is not fixed and should be reopened- for either server-based or local dtbss. (using version 1.14.815 latest_beta)

**Comment by RossPitman** [comment]
@PhilipFaure – can you please investigate this issue?

**Comment by PhilipFaure** [comment]
Sure thing, looking into it very soon

**Comment by RossPitman** [comment]
@PhilipFaure  – is this done?

**Comment by PhilipFaure** [comment]
Fixed, closing now
