### ISSUE TITLE
Reference Individuals as "NA" for ID, position, gender

### ISSUE THREAD

**Issue by Shannon-Dubay** [pantheracorp/PantheraIDS_Issues#36]
IDS seems to be reading the reference individuals incorrectly: reflecting that the individual name, position, and gender of the image is "NA". There have been a few edits to the databases through Reco/Consolidate for Timbavati, Lajuma, Tembe, Ithala, and Wel., so need to be sure that any changes to IDs was also correctly applied to the reference image for that individual; a list of edits to Tembe, Ithala, and Wel. are recorded on teams

**Comment by RossPitman** [comment]
Working on this now. Will keep you posted.

**Comment by RossPitman** [comment]
OK I might have got my wires crossed when looking at this yesterday. It seems IDS is correctly pulling the data, but the data on the server is not correct. The latest edits are in fact inserting NA into these fields.

**Comment by RossPitman** [comment]
This is a bigger problem than originally hoped.

**Comment by RossPitman** [comment]
@Shannon-Dubay – can you recall when you first detected this issue? I'm trying to isolate where the error occurs, but it's proving difficult. I thought it was during tagging an image as a reference, but I just tested this and this wasn't the case. Any ideas?

**Comment by Shannon-Dubay** [comment]
It was during the first week of June that I brought it up to Joleen- that's when I first noticed it.
________________________________

**Comment by RossPitman** [comment]
OK, do you recall what you had done in IDS to trigger this issue? It's not when tagging images. Do you have any suspicions as to what is causing it? Maybe it's caused when merging identifications to the server? I just need to find a common thread with the data sets that exhibit this issue.

**Comment by Shannon-Dubay** [comment]
OK the end of May I wrapped up the very last sites of tagging references and cropping reference images. After I finished, the databases were pushed to the server and we started moving toward server-side data usage; I believe most of the sites were available from the server by June. 

I noticed in the first week of June I went back to check on 1 or 2 ID errors and noticed that server-based databases had all reference individuals with the "NA" issue. So I tried loading the local databases from my computer (ones I had used to tag the reference individuals), and everything was fine. 

When I looked at those same dtbss from the server, the NA issue was happening. My thoughts then was that it was some bug that occurred when we pushed the dtbss to the server, or some bug with how the server-side data was stored, because there hadn't been any work done to them between when I finished the tagging/cropping and when I went to look at them on the server 2ish weeks later. Long story (sorry) short- I think it happened when we transitioned to the server. Hope that helps?

**Comment by pantheracorp** [comment]
OK thanks, that does really help.

**Comment by RossPitman** [comment]
OK thanks, that really does help.

**Comment by pantheracorp** [comment]
Fixed

**Comment by Shannon-Dubay** [comment]
Oh no. This issue is back.

Emma emailed me with the following:
_We have had issues with the references images for individuals not filtering. That is, whenever we filter for reference images it returns 0 images. We have this issue with all our survey databases. While using Manual Recognition with the 2019 S3078, the NAs have most, if not all, the reference images for that survey but they are not tagged as reference images. I know those in NA for S3078 2019 are references images because before this issue occurred we had exported those images and kept a copy._

I had a look at this myself, as their data are on the server (centralamericahub). For example, viewing S3078_2019 in Tables shows that all images where "Reference"="Yes" has "NA" for "Individual", "Position", and "Gender" too. Therefore, when she tries to view these in Manual Identification she is not able to filter for them because the images no longer have "Individual" or "Position" information. This also causes concern for her Reco-ing. It appears for both species that they individually identify (ocelots and jaguars). 

It doesn't appear that they have tagged any reference images for any 2020 databases yet, but looking at *some of the* 2019 databases, I see the following:
Databases experiencing the issue: S3078_2019, S202_2019
Databases that are OK: S3080_2019

If necessary to determine what is causing this, I can ask Emma if she notices any pattern of why some databases would be affected while others aren't. Let me know if this will help.
I see that the databases experiencing the issue are for sites in which there are 2020 data, so perhaps this is the result of Reco or Individual Reference Database?

**Comment by Shannon-Dubay** [comment]
Emma confirms that this issue was first noticed before we pushed her databases to the server, back in July.

**Comment by RossPitman** [comment]
I'm struggling to follow this to be honest. Where is she filtering for reference images?

**Comment by RossPitman** [comment]
Is this the issue? I see some records in the indvdl_obsrvtn_tbl labelled as reference images, but aren't given individual names.
![Uploading Screenshot 2020-10-13 at 12.30.39.png…]()

**Comment by Shannon-Dubay** [comment]
Your screenshot didn't upload properly

**Comment by RossPitman** [comment]
<img width="2559" alt="Screenshot 2020-10-13 at 12 30 39" src="https://user-images.githubusercontent.com/15226110/95852984-f2fccd80-0d54-11eb-9940-f4c8f5954188.png">

**Comment by Shannon-Dubay** [comment]
Yes, this is the issue. There should be (and used to be) information in all those NAs

**Comment by Shannon-Dubay** [comment]
Just a reminder about this high priority issue @RossPitman - Emma has been asking about it

**Comment by Shannon-Dubay** [comment]
I have just noticed this phenomenon in Emmas most recent local database... I will stall pushing it to the server as I don't know if the missing information will be possible to fix once on the server (or at the very least, if its easier to change in a local database). I will email this database with the subject line "For GitHub Issue 36". This database, S3078_2020, is another database on top of the previously mentioned S3078_2019 and S202_2019 that have this issue.

**Comment by Shannon-Dubay** [comment]
Just a reminder that this has been a high priority task for almost 2 months now, and Emma has asked for a status update again. I am worried that there is something within IDS that is causing data to be re-written to NA and the longer we wait on this the more databases we will have with NAs that we will have to fix

**Comment by RossPitman** [comment]
@Shannon-Dubay – please can you resend the email with subject line Github issue 36? I cannot seem to find it in my email archive.

**Comment by Shannon-Dubay** [comment]
Done

**Comment by RossPitman** [comment]
Got it, thank you.
